version: '3.5'
services:

  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf/hyperf:8.2-alpine-vedge-swoole
    working_dir: /app
    entrypoint: [ "php", "bin/hyperf.php", "start" ]
    volumes:
      - ./:/app
    ports:
      - "9501:9501"
